// lib
import Head from "next/head";
import { useRouter } from "next/navigation";

// styles
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

// components
import Button from "@/components/button";

// constants
import { APP_ROUTES } from "@/utils/routes";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();

  const redirectToTest = () => {
    router.push(APP_ROUTES.HAIR_TEST);
  };

  return (
    <>
      <Head>
        <title>Traya Healthcare</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Button onClick={redirectToTest}>Take hair test</Button>
      </main>
    </>
  );
}
